esphome:
  name: test_serial
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "ssid_name"
  password: "ssid_password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Serial Fallback Hotspot"
    password: "rU8bKud7RoTV"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: adc
    pin: A0
    name: "Water Level"
    update_interval: 2s
    icon: "mdi:water-percent"
    accuracy_decimals: 1
    unit_of_measurement: "meter"
    filters:
      - multiply: 3.3
      # - sliding_window_moving_average:
      #     window_size: 15
      #     send_every: 10
      # # - calibrate_linear:
      #   # Map 0.0 (from sensor) to 0.0 (true value)
      #   - 0.0 -> 0.89268 
      #   - 10.0 -> 1.05381 
      # - calibrate_polynomial:
      #     degree: 5
      #     datapoints:
      #   # Map 0.0 (from sensor) to 0.0 (true value)
      #     - 0.0 -> 1.26006 
      #     - 2.0 -> 1.26650 
      #     - 4.0 -> 1.31484
      #     - 6.0 -> 1.32129 
      #     - 8.0 -> 1.41475 
      #     - 10.0 -> 1.57910
      # - lambda: return (x/1.26)*100;
