esphome:
  name: PompaAir_Control
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "ssid"
  password: "password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Serial Fallback Hotspot"
    password: "rU8bKud7RoTV"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: ultrasonic
    trigger_pin: GPIO5
    echo_pin: GPIO4
    name: "Ultrasonic Sensor"
    unit_of_measurement: "meter"
    update_interval: 5s
    timeout: 4m
    
switch:
  - platform: gpio
    name: "Kendali Pompa Air"
    id: kendali_pompa_air
    pin:
      number: GPIO15
      inverted: True