esphome:
  name: PompaAir_Control
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "ssid"
  password: "password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Serial Fallback Hotspot"
    password: "rU8bKud7RoTV"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: ultrasonic
    trigger_pin: GPIO0
    echo_pin: GPIO2
    name: "Ultrasonic Sensor"
    update_interval: 10s
    timeout: 4.0m
    filters:
    - lambda: return (1-x);
    unit_of_measurement: "meter"
    
switch:
  - platform: gpio
    name: "Kendali Pompa Air"
    id: kendali_pompa_air
    pin:
      number: GPIO15
      inverted: True